// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAndkRU6iVTKGONJaTVRQoHWCVtnAAGTgA',
    appId: '1:639074607317:web:b1bfc33e020cd0419b425c',
    messagingSenderId: '639074607317',
    projectId: 'fir-flutter-codelab-ede0a',
    authDomain: 'fir-flutter-codelab-ede0a.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ede0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKraRJ98y_mt6QbLnZTrzHX9J1sUtXJ_Q',
    appId: '1:639074607317:android:850d346f2f356fcf9b425c',
    messagingSenderId: '639074607317',
    projectId: 'fir-flutter-codelab-ede0a',
    storageBucket: 'fir-flutter-codelab-ede0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3xiCkpNnYz2O5uC4CURxKn0sJ_bi8h7s',
    appId: '1:639074607317:ios:c38a9590470e4d1f9b425c',
    messagingSenderId: '639074607317',
    projectId: 'fir-flutter-codelab-ede0a',
    storageBucket: 'fir-flutter-codelab-ede0a.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3xiCkpNnYz2O5uC4CURxKn0sJ_bi8h7s',
    appId: '1:639074607317:ios:c38a9590470e4d1f9b425c',
    messagingSenderId: '639074607317',
    projectId: 'fir-flutter-codelab-ede0a',
    storageBucket: 'fir-flutter-codelab-ede0a.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
